### ISSUE TITLE
Empates

### ISSUE THREAD

**Issue by Petrigh** [Petrigh/Lazy-DM-Petrigh-s-edition#1]
Reordenar lista por modificador de iniciativa en caso de estas empatados, otra opcion seria un drag and drop

**Comment by obskur123** [comment]
@Petrigh https://github.com/Petrigh/Lazy-DM-Petrigh-s-edition/commit/9ab30890da9597422bc801e2be992948ea4732ed agregue la funcionalidad de drag and drop en este commit.
