### ISSUE TITLE
Guardar simbolos

### ISSUE THREAD

**Issue by Petrigh** [Petrigh/Lazy-DM-Petrigh-s-edition#2]
El campo iniciativa puede ser rellenado con caracteres especiales {?,@,$,%,!,etc}
Como es un string solo checkea que no tenga letras, deberia filtrar mas condiciones
Los valores aceptados deberian ser numeros y el simbolo "-" al principio en caso de ser menor que 0

**Comment by obskur123** [comment]
Creo que lo podríamos solucionar con alguna expresión regular que checkee por caracteres especiales

**Comment by obskur123** [comment]
Ahi consegui hacer que checkee por caracteres especiales, podes verlo en este commit 5d557b2f5a710e76bc6e6c7d7fc285b2c662f5e2

Ahora bien, si por ejemplo ingreso '3-' explota al demonio, debe ser una pavada checkear este caso.

**Comment by Petrigh** [comment]
El jtextfield de inicitativa ahora es un formattedtextfeld, de esta forma solo acepta enteros, el validate quedo obsoleto, pero lo deje por paja

**Comment by Petrigh** [comment]
El jtextfield de inicitativa ahora es un formattedtextfeld, de esta forma solo acepta enteros, el validate quedo obsoleto, pero lo deje por paja
